env:
    browser: true
    es6: true
    mocha: true
    node: true
extends:
    - eslint:recommended
    - plugin:react/recommended
root: true
parser: babel-eslint
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2018
    sourceType: module
plugins:
    - react
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - never
overrides:
    files: '*.js'
    rules:
        no-undefined: off
        no-unused-expressions: off
        max-len: off
        quotes: off
        prop-types: off
        'react/prop-types': 0`
